# Generated by Django 6.0.3 on 2026-03-28 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testsession',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tests.test'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testsession'),
        ),
        migrations.AlterUniqueTogether(
            name='testsession',
            unique_together={('student', 'test')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('session', 'question')},
        ),
    ]
