# Generated by Django 6.0.3 on 2026-04-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('tests', '0003_test_assigned_to_all_testassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='classes.classroom'),
        ),
    ]
